package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"

	"github.com/Dev-Etto/cv-manager/graph/model"
)

// Person is the resolver for the Person field.
func (r *queryResolver) Person(ctx context.Context) ([]*model.Person, error) {
	
	person := &model.Person{
		ID:    "1",
		Name:  "John Doe",
		Age:   30,
		Email: "test@test.com",
	}

	persons := []*model.Person{
		person,
	}

	return persons, nil

}
